[tool.poetry]
name = "ssl-checker"
version = "0.1.0"
description = ""
authors = ["rtmax0 <rtmax0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.26.0"
click = "^8.0.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ssl-checker = "ssl_checker.main:main"
